# Generated by Django 4.0.1 on 2022-01-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('buy_date', models.DateField()),
                ('updated', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
