# Generated by Django 4.0.1 on 2022-01-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_stock_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='STOCK',
        ),
    ]
