# Generated by Django 4.0.1 on 2022-01-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_stock_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='STOCKS',
        ),
    ]
